<?php

/*
 * @package Zombie Apocalypse
 * @since Zombie Apocalypse 2.0
 *
 * Root functions file
 * Calls all other required files
 * PLEASE DO NOT EDIT THIS FILE
 * use a child theme instead
 */

// variables for theme identification - do NOT edit unless you know what you are doing 
define ("_THEME_NAME", "zombie apocalypse"); 
define ("_THEME_VERSION","2.0.1");

// Load necessary admin files
require_once(get_template_directory() . "/admin/main.php"); 

// Load theme functions
require_once(get_template_directory() . "/includes/theme-functions.php");   

